apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  labels:
    app: "nginx-service"
    version: "1.0.0"
  name: "nginx-service"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: "nginx-service"
      version: "1.0.0"
  template:
    metadata:
      labels:
        app: "nginx-service"
        version: "1.0.0"
    spec:
      containers:
        - image: "nginxdemos/hello:latest"
          imagePullPolicy: "Always"
          name: "nginx-service"
          resources:
            limits:
              cpu: 500m
            requests:
              cpu: 200m
          ports:
            - protocol: TCP
              containerPort: 80
