apiVersion: "v1"
kind: "Service"
metadata:
  annotations: {}
  labels: {}
  name: "nginx-service"
spec:
  selector:
    app: "nginx-service"
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 32000
      protocol: TCP
